name: Deploy to GitHub Page

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      #- '*.*.*'

jobs:
  bulid-prod-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6
      - name: Setup Node.js version to 22.x
        uses: actions/setup-node@v6
        with: 
          node-version: '22.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci # clean install แทน npm install
      - name: Build project (production and dist folder)
        run: npm run build
      - name: Upload dist folder artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist-production
          path: dist

  auto-deploy-githun-page:
    runs-on: ubuntu-latest
    needs: bulid-prod-job
    permissions:
      contents: write
    steps:
      - name: Download dist folder artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist-production
          path: dist
      - run: ls dist
      - uses: actions/checkout@v6
      - name: Deploy to GitHub Page
        uses: SerhiiKa/VuePagesAction@1.0.4
        with:
          username: ${{github.actor}}
          reponame: ${{github.event.repository.name}}
          token: ${{secrets.GITHUB_TOKEN}}